### ISSUE TITLE
Update ttn.org/learn

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/docs#430]
- [x] Implement Hugo #427 

**Update docs to focus only on V3**
- [x] Hide content about V2 #428
- [x] Create migration from V2 to V3 video https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/248

**LoRaWAN Fundamentals content**
- [x] Update LoRaWAN 101

**Hardware**
- [x] Links buy dev kits  #429
- [x] Links to buy gateways #429

**Certifications**
- [x] Embed certifications in documentation
- [x] Include learning paths

**The Things Certification**
- [x] Add links to Udemy course: https://www.udemy.com/course/lorawan-fundamentals/

**Onboarding email series**
- [x] Update onboarding email series

**Comment by laurensslats** [comment]
Made the final (small) updates to the TTN docs 🎉
